name: workflow
on:
  push:
    branches:
      - main

jobs:

  prebuild:
    name: test, lint, type check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up dev environment
        run: >-
          pip install -e .[dev]
      - name: Test with pytest
        run: >-
          pytest -W error --cov
      - name: Lint with ruff
        run: >-
          ruff check tce/
      - name: Type check with mypy
        run: >-
          mypy tce/

  examples:
    name: run examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up examples environment
        run: >-
          pip install .[examples]
      - name: Run example scripts
        # need to skip the lammps example, github actions won't have lammps
        # need to skip ovito examples too :( github runners missing libEGL.so.1 for ovito library
        run: >-
          for file in examples/*.py; do case "$file" in *2-copper-nickel-sro.py|*iron-chrome-lammps.py|*load-dataset-and-visualize.py) ;; *) python "$file";; esac; done
        env:
          DISCORD_WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}

  build:
    needs:
      - prebuild
      - examples
    name: build distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  create-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: >-
          pip install -e .[dev]
      - name: Build pdoc documentation
        run: >-
          pdoc -d google tce/ -o _build --math --favicon "https://raw.githubusercontent.com/MUEXLY/tce-lib/refs/heads/main/assets/favicon.png" --logo "https://raw.githubusercontent.com/MUEXLY/tce-lib/refs/heads/main/assets/logo.png"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _build/

  deploy-docs:
    needs:
      - create-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: _build/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  pypi-publish:
    needs:
      - build
      - deploy-docs
    name: upload release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tce-lib
    permissions:
      id-token: write
    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc